apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: portal
    namespace: navdig
    labels:
        team: navdig
spec:
    image: {{ image }}
    port: 3000
    ingresses:
        - https://status.nav.no
    env:
        - name: NEXT_PUBLIC_BACKENDPATH
          value: "http://portalserver"
        - name: NEXT_PUBLIC_APPROVED_USERS
          value: "J162994,H161540,K146221,J104568,G124938,M106261,G121973,H166137"
        - name: NEXT_PUBLIC_OPS_ACCESS
          value: "J162994,K132081,H123099,L110875,K125327,F110862,A110886,L120166,G121973,H166137"
        - name: NPM_CONFIG_CACHE
          value: /tmp
        - name: TENANT
          value: nav.no
        - name: ENV
          value: prod
    replicas:
        min: 2
        max: 2
    azure:
        application:
            enabled: true
            allowAllUsers: true
            # optional, enum of {trygdeetaten.no, nav.no}
            # defaults to trygdeetaten.no in dev-* clusters, nav.no in production
            tenant: nav.no
            # optional
            replyURLs:
                - "https://status.nav.no/oauth2/callback"
                - "https://status.nav.no/Dashboard/Internt"
            claims:
                extra:
                    - "NAVident"
                    - "azp_name"
            # optional, defaults shown
            singlePageApplication: false
        sidecar:
            enabled: true
            autoLogin: true
            autoLoginIgnorePaths:
              - /samarbeidspartner/**
              - /_next/**
              - /api/requestGateway
              - /api/userInfo
              - /favicon.ico
              - /assets/nav-logo/png/black.png
    accessPolicy:
        outbound:
            rules:
                - application: portalserver
